version: '3.5'

services:
  boilerplate-nestjs:
    container_name: boilerplate-nestjs
    build: 
     context: .
     dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - node-modules-boilerplate-nestjs:/app/node_modules
    networks:
      - boilerplate-nestjs-network
volumes:
  node-modules-boilerplate-nestjs:
    name: node-modules-boilerplate-nestjs
networks:
  boilerplate-nestjs-network:
    name: boilerplate-nestjs-network
    driver: bridge
