version: "3.5"

services:
 boilerplate-nestjs:
  container_name: boilerplate-nestjs
  # image: colocar image
  restart: always
  ports:
   - "3333:3333"
  networks:
   - boilerplate-nestjs-network
  env_file:
    - stack.env
networks:
  boilerplate-nestjs-network:
   name: boilerplate-nestjs-network
   driver: bridge