name: CI
on:
  pull_request:
    branches:
      - production
      - development
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Checking types
        run: npm tsc --noEmit
      - name: Format code
        run: npm run format
      - name: Verify errors eslint
        run: npm run lint
      - name: Running tests
        run: npm run test
      - name: Coverage
        run: npm run test:cov
